name: Linux (gcc with EDK2)

on:
  workflow_dispatch:
    branches: [main]
  push:
    branches: [main]
    tags:
      - '**'
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: RELEASE
  COMPILER: GCC5
  EDK2_BASE: edk2-stable202411
  GCC5_ARM_PREFIX: arm-linux-gnueabi-
  GCC5_AARCH64_PREFIX: aarch64-linux-gnu-
  GCC5_RISCV64_PREFIX: riscv64-linux-gnu-
  GCC5_LOONGARCH64_PREFIX: loongarch64-unknown-linux-gnu-

jobs:
  Linux-EDK2-Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        include:
        - TARGET_TYPE: x64
          TARGET_ARCH: X64
          TARGET_PKGS: gcc-multilib
        - TARGET_TYPE: ia32
          TARGET_ARCH: IA32
          TARGET_PKGS: gcc-multilib
        - TARGET_TYPE: aa64
          TARGET_ARCH: AARCH64
          TARGET_PKGS: gcc-aarch64-linux-gnu
        - TARGET_TYPE: arm
          TARGET_ARCH: ARM
          TARGET_PKGS: gcc-arm-linux-gnueabi
        - TARGET_TYPE: riscv64
          TARGET_ARCH: RISCV64
          TARGET_PKGS: gcc-riscv64-linux-gnu
        - TARGET_TYPE: loongarch64
          TARGET_ARCH: LOONGARCH64
          TARGET_PKGS: gcc-multilib

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set version
      id: set_version
      run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT

    - name: Set up Linux environment
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install python3-setuptools nasm uuid-dev ${{ matrix.TARGET_PKGS }}
        if [[ "${{ matrix.TARGET_ARCH }}" == "LOONGARCH64" ]]; then
          curl -L -O https://github.com/loongson/build-tools/releases/download/2024.11.01/x86_64-cross-tools-loongarch64-binutils_2.43.1-gcc_14.2.0-glibc_2.40.tar.xz
          tar -xJf x86_64-cross-tools-loongarch64-binutils_2.43.1-gcc_14.2.0-glibc_2.40.tar.xz
          echo "$PWD/cross-tools/bin" >> "$GITHUB_PATH"
        fi

    - name: Set up EDK2
      run: |
        git clone --recursive https://github.com/tianocore/edk2.git -b ${{ env.EDK2_BASE }}
        make -C edk2/BaseTools

    - name: Build UEFI bootloader
      run: |
        export WORKSPACE=$PWD
        export PACKAGES_PATH=$WORKSPACE:$WORKSPACE/edk2
        source edk2/edksetup.sh
        build -a ${{ matrix.TARGET_ARCH }} -b ${{ env.BUILD_TYPE }} -t ${{ env.COMPILER }} -p Md5SumPkg.dsc
        mv Build/${{ env.BUILD_TYPE }}_${{ env.COMPILER }}/${{ matrix.TARGET_ARCH }}/Md5Sum.efi boot${{ matrix.TARGET_TYPE }}.efi

    - name: Display SHA-256
      run: sha256sum *.efi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.TARGET_TYPE }}
        path: ./*.efi

    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "**UEFI md5sum ${{ steps.set_version.outputs.version }}**"
        files: ./*.efi
